name: Tests


on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8','3.9']
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install poetry && poetry install
      - name: Build python package
        run: poetry build
      - name: Build docs
        run: poetry run mkdocs build
      - name: Run tests
        run: poetry run pytest
      - uses: codecov/codecov-action@v1
        with:
          env_vars: OS, PYTHON
          fail_ci_if_error: true

        

  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test docker build
        run: docker build -t pyproject . 
      - name: Test inside container
        run: docker run pyproject poetry run pytest
    
